In [1]:
from riotwatcher import LolWatcher, ApiError
import pandas as pd
import csv
import playerinformation

In [2]:
# global variables
api_key = "RGAPI-595ca1c5-ceb8-4de2-8464-7eb8635fbf85"
watcher = LolWatcher(api_key, default_match_v5=True)
my_region = 'EUW1'

property 'default_match_v5' has been deprecated and can be removed

In [3]:
# get player name from csv
data = pd.read_csv ("EUW_matches.csv")
my_matches = data['id'].tolist()

In [5]:
playerinformation.get_information(my_matches, watcher, 3040, 4632, "EUW_match_information_2.csv")

,gameId,gameDuration,gameVersion,platformId,season,winner,1st_baron,1st_dragon,1st_inhibitor,1st_riftHerald,...,t2_baron_kills,t2_champ_kills,t2_dragon_kills,t2_inhibitor_kills,t2_riftHerald_kills,t2_tower_kills,t2_team_assists,t2_team_gold_earn,t2_team_gold_spen,t2_team_kda
0,5539686518,2458,11.22.406.3587,EUW1,11,1,2,2,2,1,...,2,35,5,3,0,8,47,78341,75060,2.102564
1,5539731659,1737,11.22.406.3587,EUW1,11,1,1,2,1,1,...,0,19,2,0,0,4,26,50905,48838,1.451613
2,5540212367,2032,11.22.406.3587,EUW1,11,1,1,1,1,1,...,0,34,2,0,0,4,43,62403,60293,1.638298
3,5540078457,964,11.22.406.3587,EUW1,11,1,0,2,0,0,...,0,10,1,0,0,0,8,25681,23755,0.782609
4,5540685027,1630,11.22.406.3587,EUW1,11,1,0,2,1,1,...,0,14,2,0,0,2,18,45068,44220,0.888889
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1585,5537934278,1534,11.22.406.3587,EUW1,11,1,0,2,1,2,...,0,25,1,0,1,2,25,44485,41905,1.136364
1586,5537053358,203,11.22.406.3587,EUW1,11,1,0,0,0,0,...,0,1,0,0,0,0,1,5055,2000,2.000000
1587,5536803125,1825,11.22.406.3587,EUW1,11,1,1,1,1,1,...,0,27,1,0,0,3,31,53740,51200,1.160000
1588,5501291740,1280,11.20.400.7328,EUW1,11,1,0,2,1,1,...,0,9,1,0,0,1,5,29741,30025,0.437500
1589,5498984172,1507,11.20.400.7328,EUW1,11,2,0,2,2,1,...,0,55,3,1,1,7,58,56550,49600,5.650000