In [5]:
from riotwatcher import LolWatcher, ApiError
import pandas as pd
import csv
import playerinformation

In [6]:
# global variables
api_key = "RGAPI-595ca1c5-ceb8-4de2-8464-7eb8635fbf85"
watcher = LolWatcher(api_key, default_match_v5=True)
my_region = 'EUN1'

property 'default_match_v5' has been deprecated and can be removed

In [7]:
# get player name from csv
data = pd.read_csv ("EUNE_matches.csv")
my_matches = data['id'].tolist()

In [9]:
playerinformation.get_information(my_matches, watcher, 756, 1512, "EUNE_match_information_1.csv")

,gameId,gameDuration,gameVersion,platformId,season,winner,1st_baron,1st_dragon,1st_inhibitor,1st_riftHerald,...,t2_baron_kills,t2_champ_kills,t2_dragon_kills,t2_inhibitor_kills,t2_riftHerald_kills,t2_tower_kills,t2_team_assists,t2_team_gold_earn,t2_team_gold_spen,t2_team_kda
0,2947163922,1247,11.20.400.7328,EUN1,11,1,0,2,1,1,...,0,21,1,0,0,1,16,36888,35325,1.027778
1,2956011375,1789,11.21.403.3002,EUN1,11,2,1,1,2,0,...,0,42,1,2,0,9,56,63609,54530,3.266667
2,2953636673,1626,11.20.400.7328,EUN1,11,1,1,1,1,1,...,0,18,0,0,0,2,17,41809,40320,1.129032
3,2961916410,3161,11.21.403.3002,EUN1,11,1,1,2,2,1,...,0,63,3,1,0,6,73,92336,86925,1.462366
4,2951441916,1386,11.20.400.7328,EUN1,11,1,0,1,1,0,...,0,16,0,0,0,1,12,32634,29093,0.717949
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
751,2911305259,2278677,11.16.390.1945,EUN1,11,2,2,1,2,2,...,1,50,4,2,1,9,69,74535,64675,2.975000
752,2911348895,1839260,11.16.390.1945,EUN1,11,2,2,2,2,2,...,1,28,1,2,1,10,51,59229,48575,2.821429
753,2965263660,1349,11.22.406.3587,EUN1,11,2,2,2,2,1,...,1,29,3,2,0,10,17,47346,38635,4.600000
754,2952380786,1978,11.20.400.7328,EUN1,11,1,0,1,1,2,...,0,22,2,0,1,2,21,52516,50133,1.162162
755,2961842159,2218,11.21.403.3002,EUN1,11,1,1,1,1,2,...,0,31,1,0,1,1,46,60068,56400,1.878049